spring.application.name=ParamShavak
server.port:8081
spring.data.mongodb.uri=mongodb://localhost:27017/paramshavak
spring.data.mongodb.auto-index-creation=true

server.servlet.session.timeout=30m

JWT_SECRET_KEY=YmFza2V0b3duZXJzZXZlbndyb3RlbmVlZGxlc3VpdGRyZWFtdG9waWNhbG1vc3RtYXQ=


spring.mail.host=smtp.cdac.in
spring.mail.port=587
spring.mail.username=hvaibhav@cdac.in
spring.mail.password=Cdac@27012001@11052000
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




sms.twilio.accountSid=your-twilio-account-sid
sms.twilio.authToken=your-twilio-auth-token
sms.twilio.phoneNumber=your-twilio-phone-number





